openapi: 3.0.0
info:
  title: Bookstore API
  version: 1.0.0
  description: API for managing a bookstore inventory

paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: A list of books
    post:
      summary: Add a new book
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
      responses:
        '201':
          description: Book added
  /books/{id}:
    get:
      summary: Get a book by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Book found
        '404':
          description: Book not found
